project:
  type: website
  output-dir: docs

website:
  title: "Introduction to R"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

babelquarto:
  languagelinks: navbar
  languagecodes:
    - name: es
      text: "Español"
    - name: en
      text: "English"
  mainlanguage: en
  languages: [es]

title-es: "Introducción a R"
description-es: "Una introducción práctica al manejo y visualización de datos"

lang: en